import { NextRequest, NextResponse } from "next/server";
import { getToken } from "next-auth/jwt";
import { generateTTS, checkProviderAvailability } from "@/lib/ai-providers";

/**
 * MELO TTS API — Multi-provider text-to-speech
 * 
 * Tries providers in order: OpenAI TTS → ElevenLabs → Mistral → z-ai CLI
 * Falls back automatically if any provider fails.
 * Auth required — TTS generation costs credits.
 */
export async function POST(req: NextRequest) {
  // Auth check — TTS generation is resource-intensive
  const token = await getToken({ req, secret: process.env.NEXTAUTH_SECRET });
  if (!token?.sub) {
    return NextResponse.json(
      { success: false, error: { code: "UNAUTHORIZED", message: "Authentification requise" } },
      { status: 401 }
    );
  }

  try {
    const body = await req.json();
    const { action, text } = body;

    if (action === "tts" && text) {
      try {
        console.log(`[melo-tts] Request: ${text.slice(0, 50)}...`);
        
        // Use multi-provider TTS system
        const result = await generateTTS(text, `melo-${Date.now()}.wav`);
        
        console.log(`[melo-tts] Generated by provider: ${result.provider}`);
        return NextResponse.json({ 
          audioUrl: result.audioUrl,
          provider: result.provider,
        });
      } catch (err) {
        console.error("[melo-tts] All TTS providers failed:", err);
        return NextResponse.json({ 
          audioUrl: null, 
          fallback: true,
          error: "TTS non disponible, veuillez réessayer plus tard",
        });
      }
    }

    if (action === "faq-search") {
      const { searchFAQ } = await import("@/components/melo/faq-data");
      const results = searchFAQ(text || "");
      return NextResponse.json({ results: results.slice(0, 5) });
    }

    if (action === "providers") {
      // New endpoint: check which providers are available
      const availability = checkProviderAvailability();
      return NextResponse.json({ availability });
    }

    return NextResponse.json({ error: "Action non reconnue" }, { status: 400 });
  } catch {
    return NextResponse.json({ error: "Erreur serveur" }, { status: 500 });
  }
}
